export {default as Navbar } from "./NavBar"
export {default as Footer} from "./Footer"
export {default as HomePage} from "./HomePage"
export {default as CryptoCurrency} from "./CryptoCurrency"
export {default as CryptoDetails} from "./CryptoDetails"
export {default as Exchanges} from "./Exchanges"
export {default as News} from "./News"